include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_final_locals: true
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_renaming_method_parameters: true
